name: CI for Portfolio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  super-linter:
    runs-on: ubuntu-latest
    name: Lint HTML with Super-Linter
    permissions:
      contents: read
      packages: read
      statuses: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
  
  linchee-links:
    name: Check links with linchee
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run lychee link checker.
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
      
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue